name: Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Backend Image
        run: |
          docker build -t your-dockerhub-letsadvertize/vscodeautomation-backend:latest ./backend
          docker push your-dockerhub-letsadvertize/vscodeautomation-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t your-dockerhub-letsadvertize/vscodeautomation-frontend:latest ./frontend
          docker push your-dockerhub-letsadvertize/vscodeautomation-frontend:latest
